/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "Platform_Types.h"
//register address

#define RCC_BASE 	0x40021000
#define GPIOA_BASE 	0x40010800

#define RCC_APB2ENR *(volatile uint32_t*)( RCC_BASE + 0x18)
#define GPIOA_CRH 	*(volatile uint32_t*)( GPIOA_BASE + 0x04)
#define GPIOA_ODR	*(volatile uint32_t*)( GPIOA_BASE + 0x0C)


typedef union
{
	vuint32_t All_Fields;
	struct{
		vuint32_t reserved:13;
		vuint32_t pin13:1;

	}pin;


}R_ODR_t;

volatile R_ODR_t* R_ODR = (volatile R_ODR_t*)(GPIOA_BASE + 0x0C);

typedef union{
	 
vuint32_t ALL_PORTS;
	struct {
		 
vuint32_t reserved : 20;
	//vuint32_t pin20_23 :4;
	 
vuint32_t pin2 :1;
		 
vuint32_t pin21 :1;
		 
vuint32_t pin22 :1;
		 
vuint32_t pin23 :1;
	}pin;
}R_CRH;
volatile R_CRH * R_CRH_T= (volatile R_CRH *)(GPIOA_BASE+0x04);

typedef union{
	 
vuint32_t ALL_PORTS;
	struct {
		 
vuint32_t reserved :2;
		 
vuint32_t pin2 :1;
	}pin;
}R_APB2ENR;
volatile R_APB2ENR * R_APB2ENR_T= (volatile R_APB2ENR *)(RCC_BASE+0x18);

int main(void)
{
	volatile int x;
	R_APB2ENR_T->pin.pin2=1;
//	RCC_APB2ENR |= 1<<2;
	R_CRH_T->pin.pin20=0;
	R_CRH_T->pin.pin21=1;
	R_CRH_T->pin.pin22=0;
	R_CRH_T->pin.pin23=0;

//	GPIOA_CRH 	&=0xff0fffff;
//	GPIOA_CRH  |=0x00200000;

	while(1)
	{
		R_ODR->pin.pin13 = 1;
//		GPIOA_ODR |=(1<<13);
		for(x=0;x<5000;x++);
		R_ODR->pin.pin13 =0;
//		GPIOA_ODR &=~(1<<13);
		for(x=0;x<5000;x++);
	}
	return 0 ;
}
